# Generated by Django 4.2.3 on 2023-07-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='visited_countries',
            field=models.ManyToManyField(blank=True, related_name='visits', to='core.country'),
        ),
    ]
